Repository neelnanda-io/TransformerLens, pull requests merged in 2023-10, with the labels that each got.

#395 Move towards consistent commenting/docstring style
  transformer_lens/ActivationCache.py
  transformer_lens/HookedTransformer.py
Labels: documentation

#336 Add `hook_attn_in`
  tests/unit/test_hooks.py
  transformer_lens/HookedTransformer.py
  transformer_lens/HookedTransformerConfig.py
  transformer_lens/components.py
Labels: enhancement

#334 Fix tokenization in utils.test_prompt
  tests/unit/test_utils.py
  transformer_lens/utils.py
Labels: seen_by_maintainers
