Repository neelnanda-io/TransformerLens, pull requests merged in 2023-01, with the labels that each got.

#117 Implement permanent hooks
  transformer_lens/hook_points.py
  transformer_lens/tests/test_hooks.py
Labels: patch

#142 Tracr demo
  Tracr_to_Transformer_Lens_Demo.ipynb
Labels: demo

#143 Added option to stop running the model at an earlier layer
  transformer_lens/HookedTransformer.py
  transformer_lens/tests/test_stop_at_layer.py
Labels: enhancement

#141 let 'get_dataset' function pass kwargs
  transformer_lens/HookedTransformer.py
  transformer_lens/utils.py
Labels: enhancement
